package me.ethan.interception.api.interfaces;

public interface InterceptionFilter {
    int INTERCEPTION_KEY_DOWN = 0x00;
    int INTERCEPTION_KEY_UP = 0x01;
    int INTERCEPTION_KEY_E0 = 0x02;
    int INTERCEPTION_KEY_E1 = 0x04;
    int INTERCEPTION_KEY_TERMSRV_SET_LED = 0x08;
    int INTERCEPTION_KEY_TERMSRV_SHADOW = 0x10;
    int INTERCEPTION_KEY_TERMSRV_VKPACKET = 0x20;
    int INTERCEPTION_FILTER_KEY_NONE = 0x0000;
    int INTERCEPTION_FILTER_KEY_ALL = 0xFFFF;
    int INTERCEPTION_FILTER_KEY_DOWN = INTERCEPTION_KEY_UP;
    int INTERCEPTION_FILTER_KEY_UP = INTERCEPTION_KEY_UP << 1;
    int INTERCEPTION_FILTER_KEY_E0 = INTERCEPTION_KEY_E0 << 1;
    int INTERCEPTION_FILTER_KEY_E1 = INTERCEPTION_KEY_E1 << 1;
    int INTERCEPTION_FILTER_KEY_TERMSRV_SET_LED = INTERCEPTION_KEY_TERMSRV_SET_LED << 1;
    int INTERCEPTION_FILTER_KEY_TERMSRV_SHADOW = INTERCEPTION_KEY_TERMSRV_SHADOW << 1;
    int INTERCEPTION_FILTER_KEY_TERMSRV_VKPACKET = INTERCEPTION_KEY_TERMSRV_VKPACKET << 1;

    int INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN = 0x001;
    int INTERCEPTION_MOUSE_LEFT_BUTTON_UP = 0x002;
    int INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN = 0x004;
    int INTERCEPTION_MOUSE_RIGHT_BUTTON_UP = 0x008;
    int INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN = 0x010;
    int INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP = 0x020;

    int INTERCEPTION_MOUSE_BUTTON_1_DOWN = INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN;
    int INTERCEPTION_MOUSE_BUTTON_1_UP = INTERCEPTION_MOUSE_LEFT_BUTTON_UP;
    int INTERCEPTION_MOUSE_BUTTON_2_DOWN = INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN;
    int INTERCEPTION_MOUSE_BUTTON_2_UP = INTERCEPTION_MOUSE_RIGHT_BUTTON_UP;
    int INTERCEPTION_MOUSE_BUTTON_3_DOWN = INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN;
    int INTERCEPTION_MOUSE_BUTTON_3_UP = INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP;

    int INTERCEPTION_FILTER_MOUSE_NONE = 0x0000;
    int INTERCEPTION_FILTER_MOUSE_ALL = 0xFFFF;

    int INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_DOWN = INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN;
    int INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_UP = INTERCEPTION_MOUSE_LEFT_BUTTON_UP;
    int INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_DOWN = INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN;
    int INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_UP = INTERCEPTION_MOUSE_RIGHT_BUTTON_UP;
    int INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_DOWN = INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN;
    int INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_UP = INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP;

    int INTERCEPTION_FILTER_MOUSE_BUTTON_1_DOWN = INTERCEPTION_MOUSE_BUTTON_1_DOWN;
    int INTERCEPTION_FILTER_MOUSE_BUTTON_1_UP = INTERCEPTION_MOUSE_BUTTON_1_UP;
    int INTERCEPTION_FILTER_MOUSE_BUTTON_2_DOWN = INTERCEPTION_MOUSE_BUTTON_2_DOWN;
    int INTERCEPTION_FILTER_MOUSE_BUTTON_2_UP = INTERCEPTION_MOUSE_BUTTON_2_UP;
    int INTERCEPTION_FILTER_MOUSE_BUTTON_3_DOWN = INTERCEPTION_MOUSE_BUTTON_3_DOWN;
    int INTERCEPTION_FILTER_MOUSE_BUTTON_3_UP = INTERCEPTION_MOUSE_BUTTON_3_UP;

    int INTERCEPTION_FILTER_MOUSE_MOVE = 0x1000;
}
